fetch VCS type

diff --git a/src/jobs/workflow-collector.yml b/src/jobs/workflow-collector.yml
--- a/src/jobs/workflow-collector.yml
+++ b/src/jobs/workflow-collector.yml
@@ -85,7 +85,22 @@ steps:
               ###
               # Process Job api 1.1 Data
               ###
-              JOB_DATA_RAW=$(curl -s "https://circleci.com/api/v1.1/project/:vcs-type/:username/:project/$JOB_NUMBER?circle-token=$CIRCLE_TOKEN")
+              # GET URL PATH DATA
+              VCS_SHORT=$(echo $CIRCLE_BUILD_URL | cut -d"/" -f4)
+              case $VCS_SHORT in
+                gh)
+                  VCS=github
+                  ;;
+                bb)
+                  VCS=bitbucket
+                  ;;
+                *)
+                  echo "No VCS found. Error"
+                  exit 1
+                  ;;
+              esac
+
+              JOB_DATA_RAW=$(curl -s "https://circleci.com/api/v1.1/project/$VCS/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$JOB_NUMBER?circle-token=$CIRCLE_TOKEN")
               echo $JOB_DATA_RAW > /tmp/sumologic-logs/job-collector.json
               curl -s -X POST -T /tmp/sumologic-logs/job-collector.json $<< parameters.job-collector >>
               ###
@@ -157,7 +172,7 @@ steps:
               ###
               # Process Job api 1.1 Data
               ###
-              JOB_DATA_RAW=$(curl -s "https://circleci.com/api/v1.1/project/:vcs-type/:username/:project/$JOB_NUMBER?circle-token=$CIRCLE_TOKEN")
+              JOB_DATA_RAW=$(curl -s "https://circleci.com/api/v1.1/project/:vcs-type/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$JOB_NUMBER?circle-token=$CIRCLE_TOKEN")
               # debug
               echo debug
               echo "---"
